baseURL = "https://www.hancezhang.blog/"
canonifyURLs = true
buildFuture = true
theme = 'PaperMod'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
    title = "Hance Zhang's Blog"
    contentDir = "content/en"
    [languages.en.params]
      homeInfoParams = {Title = "ğŸ‘‹ Welcome to Hance Zhang's Blog", Content = "I write about learnings in leadership, product building, and investment. I'm currently based in Tokyo, DM me via X!"}
    [[languages.en.menu.main]]
      name = "Posts"
      url = "/posts/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Archive"
      url = "/archives/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Search"
      url = "/search/"
      weight = 3

  [languages.zh]
    languageCode = "zh-cn"
    languageName = "ä¸­æ–‡"
    weight = 2
    title = "Hance Zhangçš„åšå®¢"
    contentDir = "content/zh"
    [languages.zh.params]
      homeInfoParams = {Title = "ğŸ‘‹ æ¬¢è¿æ¥åˆ° Hance Zhangçš„åšå®¢", Content = "æˆ‘æ’°å†™å…³äºé¢†å¯¼åŠ›ã€äº§å“æ€è€ƒå’ŒæŠ•èµ„æ–¹é¢çš„å­¦ä¹ å¿ƒå¾—ã€‚ç›®å‰baseä¸œäº¬ï¼Œå¯ä»¥é€šè¿‡Xç§ä¿¡æˆ‘ï¼æ–‡ç« åŸæ–‡æ˜¯è‹±æ–‡ï¼Œä¸­æ–‡éƒ½æ˜¯AIç¿»è¯‘çš„"}
    [[languages.zh.menu.main]]
      name = "æ–‡ç« "
      url = "/posts/"
      weight = 1
    [[languages.zh.menu.main]]
      name = "å½’æ¡£"
      url = "/archives/"
      weight = 2
    [[languages.zh.menu.main]]
      name = "æœç´¢"
      url = "/search/"
      weight = 3

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  showtoc = false
  showtranslations = true # For PaperMod language switcher
  displayFullLangName = true

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/hance_zhang7"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:hanszhang717@gmail.com"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    includeMatches = true
    findAllMatches = false
    minMatchCharLength = 2
    threshold = 0.2
    location = 0
    distance = 100
    keys = ["title"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
